# site settings
title: Theatro
subtitle: Melpômene
email: colette@colettedantas.com
description: Acendem-se as primeiras luzes do Theatro Melpômene. Em breve o teatro de ‘pau’ vai reviver suas memórias no território que herdou sua vocação, a partir de seus vestígios materiais e culturais.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Colette Dantas
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/colettedantas

# build settings
markdown: kramdown

sass:
  style: compressed
